POST http://localhost:3312/api/movies/
Content-Type: application/json

{
    "title": "Jurassic park",
    "director": "Thomas",
    "release_year": 2032,
    "image": "https://cdn-icons-png.flaticon.com/512/29/29072.png"

}

###

GET http://localhost:3312/api/movies/

###

PUT http://localhost:3312/api/movies/2
Content-Type: application/json

{
    "title": "Titanic",
    "director": "Cameron",
    "release_year": 1997,
    "image": "https://antreducinema.fr/wp-content/uploads/2020/04/Titanic.jpg"

}

###
DELETE  http://localhost:3312/api/movies/1